spring:
  application:
    name: ticket-system

  datasource:
    url: jdbc:postgresql://localhost:5432/tickets
    username: postgres
    password: "0000"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

llm:
  api-key: ${GEMINI_API_KEY}
  api-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent